In [1]:
print('hello')

hello


In [2]:
import numpy as np

In [3]:
#scalar arithmetic
arr = np.array([2,4,6])
print(arr * 2)
print(arr + 2)
print(arr - 2)
print(arr * 2)
print(arr / 2)
print(arr ** 2)


[ 4  8 12]
[4 6 8]
[0 2 4]
[ 4  8 12]
[1. 2. 3.]
[ 4 16 36]


In [7]:
#Vectorized math function 
arr = np.array([2,4,6])
print(np.sqrt(arr))


[1.41421356 2.         2.44948974]


In [8]:
arr = np.array([2.6 ,4.7 ,6.3])
print(np.round(arr))


[3. 5. 6.]


In [9]:
arr = np.array([2.6 ,4.7 ,6.3])
print(np.floor(arr))

[2. 4. 6.]


In [10]:
arr = np.array([2.6 ,4.7 ,6.3])
print(np.ceil(arr))

[3. 5. 7.]


In [14]:
#Element -wise arithmatic
arr1 = np.array([2, 4, 6])
arr2 = np.array([1, 2, 3])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)


[3 6 9]
[1 2 3]
[ 2  8 18]


In [18]:
#Comparison operator
Marks = np.array([45, 74, 66, 87])
print(Marks >=50)
print(Marks < 50)

Marks[0] = 30
print(Marks)

Marks[Marks < 50] = 0
print(Marks)

[False  True  True  True]
[ True False False False]
[30 74 66 87]
[ 0 74 66 87]
