# NumPy Arrays & Operations - Complete Guide

## Introduction
This notebook provides a comprehensive guide to working with NumPy arrays. You'll learn how to:
- Create arrays (1D, 2D, and multidimensional)
- Perform mathematical operations on arrays
- Use statistical functions
- Index and manipulate array dimensions
- Compare NumPy with standard Python lists

**Prerequisites:** Basic knowledge of Python

---

In [ ]:
# Simple string concatenation example
print('hello' + 'world')

helloworld


In [4]:
import numpy as np

## Section 1: Getting Started with NumPy

### What is NumPy?
NumPy is a Python library for numerical computing that provides:
- N-dimensional array objects (ndarrays)
- Broadcasting functions
- Tools for integrating C/C++ and Fortran code
- Linear algebra, Fourier transform, and random number capabilities

### Installing NumPy
```bash
pip install numpy
```

Let's import NumPy and check its version:

In [ ]:
# Import NumPy library
import numpy as np

# Create a 1D array from a Python list
a = np.array([1, 2, 3, 4])  # 1D Array
print("1D Array:")
print(a)
print(f"\nNumPy Version: {np.__version__}")

[1 2 3 4]
2.4.4


In [ ]:
# Create a 2D array (2 rows, 2 columns)
b = np.array([[1, 2], [3, 4]])  # 2D Array (Matrix)
print("2D Array (Matrix):")
print(b)

[[1 2]
 [3 4]]


## Section 2: Creating Arrays

### 2D Arrays
A 2D array is like a matrix with rows and columns.

In [ ]:
# Generate array with values from 1 to 9 (stop value is exclusive)
# Syntax: np.arange(start, stop, step)
array_seq = np.arange(1, 10)
print("Array from 1 to 9:")
print(array_seq)

[1 2 3 4 5 6 7 8 9]


### Generating Array Sequences
Use `np.arange()` to generate arrays with evenly spaced values within a specified range.

In [ ]:
# Create a 1D array
n = np.array([1, 2, 3])

# Perform element-wise mathematical operations
print("Original array:", n)
print("Multiply by 2:", n * 2)
print("Add 2:", n + 2)
print("Integer division by 2:", n // 2)

[2 4 6]
[3 4 5]
[0 1 1]


## Section 3: Mathematical Operations on Arrays

### Element-wise Operations
NumPy allows you to perform mathematical operations on all array elements at once (vectorization).

In [ ]:
# Create an array for statistical analysis
n = np.array([1, 2, 3, 4])

# Calculate mean (average) and sum
mean_value = np.mean(n)
sum_value = np.sum(n)

print(f"Array: {n}")
print(f"Mean (Average): {mean_value}")
print(f"Sum: {sum_value}")

2.5
10


### Statistical Functions
NumPy provides built-in functions for common statistical calculations.

In [ ]:
# Python List behavior: Multiplying a list repeats it, not the elements!
lst = [2, 4, 6, 8]
doublelist = lst * 2
print("Python List * 2 (repeats the list):")
print(doublelist)
print(f"Length: {len(doublelist)}")

[2, 4, 6, 8, 2, 4, 6, 8]


## Section 4: NumPy Arrays vs Python Lists

### Why NumPy is Better than Lists
NumPy arrays are more efficient than Python lists for numerical operations. Let's see the difference:

In [ ]:
# NumPy Array behavior: Multiplying multiplies each element!
numplist = np.array([2, 4, 6, 8])
doublelist = numplist * 2
print("\nNumPy Array * 2 (multiplies each element):")
print(doublelist)
print(f"Length: {len(doublelist)}")

[ 4  8 12 16]


In [ ]:
# Check the number of dimensions in an array
numplist = np.array([2, 4, 6, 8])
print(f"Array: {numplist}")
print(f"Number of dimensions (ndim): {numplist.ndim}")
print(f"Shape of array: {numplist.shape}")

1


## Section 5: Array Dimensions and Indexing

### Checking Array Dimensions
Use `.ndim` to check the number of dimensions and `.shape` to check the shape of an array.

In [ ]:
# Create a 3D array with shape (3, 3, 3) - Depth=3, Rows=3, Columns=3
numplist = np.array([
    [  # Depth 0
        ['A', 'B', 'C'],
        ['D', 'E', 'F'],
        ['G', 'H', 'I']
    ],
    [  # Depth 1
        ['J', 'K', 'L'],
        ['M', 'N', 'O'],
        ['P', 'Q', 'R']
    ],
    [  # Depth 2
        ['S', 'T', 'U'],
        ['V', 'W', 'X'],
        ['Y', 'Z', ' ']
    ]
])

print(f"Array shape: {numplist.shape}")
print(f"Number of dimensions: {numplist.ndim}\n")

# Example 1: Extract letters and form a word using multidimensional indexing
# Accessing: [depth, row, column]
text = (numplist[1, 0, 0] +  # J
        numplist[0, 0, 0] +  # A
        numplist[2, 1, 0] +  # V
        numplist[0, 0, 0])   # A
print(f"Word 1: {text}")

# Example 2: Form another word
word = (numplist[2, 0, 0] +  # S
        numplist[0, 1, 1] +  # E
        numplist[0, 2, 1] +  # H
        numplist[0, 0, 0] +  # A
        numplist[1, 2, 2] +  # R
        numplist[1, 1, 1])   # N
print(f"Word 2: {word}")

# Example 3: Form a third word
word = (numplist[1, 2, 0] +  # P
        numplist[2, 2, 0] +  # Y
        numplist[2, 0, 1] +  # T
        numplist[0, 2, 1] +  # H
        numplist[1, 1, 2] +  # O
        numplist[1, 1, 1])   # N
print(f"Word 3: {word}")

JAVA
SEHAR
PYTHON


In [ ]:
## Summary

In this notebook, you learned:

- Array Creation: How to create 1D, 2D, and multidimensional arrays  
- Array Generation: Using np.arange() and other functions  
- Mathematical Operations: Vectorized operations on arrays (much faster than loops!)  
- Statistical Functions: Mean, sum, and other built-in functions  
- NumPy vs Lists: Why NumPy is superior for numerical computing  
- Array Properties: Using .ndim and .shape to inspect arrays  
- Array Indexing: Accessing elements in multidimensional arrays  

## Next Steps

- Explore more NumPy functions like reshape(), flatten(), and transpose()
- Learn about broadcasting for operations between arrays of different shapes
- Study linear algebra operations with np.linalg
- Practice with real-world datasets

---

**Author:** Sehar Shahzadi  
**Last Updated: 2026  
**License:** Open Source