In [1]:
print('Hello numpy')

Hello numpy


In [2]:
import numpy as np


In [3]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
arr = np.zeros((2,3,4))
print(arr)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
arr = np.zeros((3,4))
print(arr)

In [7]:
arr = np.ones((2,3,4))
print(arr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [8]:
arr = np.full((2,3,4),5 )
print(arr)

[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]


In [10]:
arr = np.eye(4)
print(arr)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
arr = np.arange(0,100,2)
print(arr)


[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [21]:
arr = np.linspace(0,100,10)
print(arr)


[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [ ]:
#Aggregate function : summarize data and return a sigle value
arr = np.array([ [1,2,3,4,5],
                 [6,7,8,9,10] ])

print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))


55
5.5
1
10
0
9


In [29]:
arr = np.array([ [1,2,3,4,5],
                 [6,7,8,9,10] ])
print(np.sum(arr,axis=1))


[15 40]
