In [1]:
import numpy as np

In [3]:
#filtering : process of selecting elements from an array that match a given condition
marks = np.array([ [44,56,92,75,32,89 ],
                   [83,58,39,68,79,95 ] ])

passStudents = marks[marks > 50]
#print(passStudents)
failStudents = marks[marks < 50]
#print(failStudents)
cgrad = marks[(marks >= 50) & (marks <= 70)]
print(cgrad)
bgrad = marks[(marks >= 70) & (marks <= 80)]
print(bgrad)
agrad = marks[(marks >= 80) & (marks <= 100)]
print(agrad)

[56 58 68]
[75 79]
[92 89 83 95]


In [8]:
#saving and loading arrays

marks = np.array([ [44,56,92,75,32,89 ],
                   [83,58,39,68,79,95 ] ])


marks2 = np.array([ [26,56,92,75,32,89 ],
                   [27,58,39,68,79,95 ] ])

#np.save('marks',marks) # for saving single array 
np.savez('MultipleMarks',marks,marks2) # for saving multiple array
print('saving marks')

saving marks


In [9]:
#Compressed file save for less memory 
np.savez_compressed('MultipleMarks-compressed',marks,marks2) # for saving multiple array

In [ ]:
#load compressed file
array = np.load('MultipleMarks-compressed.npz')
print(array)


NpzFile 'MultipleMarks-compressed.npz' with keys: arr_0, arr_1
[[44 56 92 75 32 89]
 [83 58 39 68 79 95]]


In [19]:
#access compressed file data using keys 
newmarks = array['arr_0']
#print(newmarks)

newmarks2 = array['arr_1']
print(newmarks2)

[[26 56 92 75 32 89]
 [27 58 39 68 79 95]]


In [5]:
np.save('S:\\marks',marks)
#print('saving marks')

array = np.load('s:\\marks.npy')
print(array)

[[44 56 92 75 32 89]
 [83 58 39 68 79 95]]


In [ ]:
arr = np.load('S:\\marks.npy') #Load  data frome hard disk using path
print(arr)  #Retrive data 


[[44 56 92 75 32 89]
 [83 58 39 68 79 95]]
