# NumPy Array Reshaping & Slicing - Complete Guide

## Introduction
This notebook explores two fundamental operations for manipulating NumPy arrays:
- **Reshaping**: Changing the dimensions of an array without changing its data
- **Slicing**: Extracting specific elements or portions of an array

These techniques are essential for:
- Preparing data for machine learning models
- Reorganizing data structures
- Efficient data extraction
- Matrix operations and linear algebra

**Prerequisites:** Basic knowledge of NumPy arrays and dimensions

---

In [2]:
# Let's start with a simple greeting
print('NumPy Reshaping & Slicing Guide')

NumPy Reshaping & Slicing Guide


## Step 1: Setup - Import NumPy

In [2]:
import numpy as np

## Step 2: Array Reshaping

### What is Reshaping?
Reshaping changes the dimensions of an array without changing its data. The total number of elements must remain the same.

### Reshape Syntax
```python
np.array.reshape(new_shape)
```

**Note:** Using `-1` lets NumPy calculate one dimension automatically based on the array size.

In [4]:
# Create a 1D array with 12 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Original 1D array:")
print(f"Shape: {arr.shape}")
print(f"Array: {arr}\n")

# Reshape to a column vector (12 rows, 1 column)
# Using -1 tells NumPy to calculate this dimension automatically
arr_reshaped = arr.reshape(-1, 1)
print("Reshaped to column vector (12×1):")
print(f"Shape: {arr_reshaped.shape}")
print("Array:")
print(arr_reshaped)

Original 1D array:
Shape: (12,)
Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to column vector (12×1):
Shape: (12, 1)
Array:
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [6]:
# Example 1: Reshape 1D to 2D (3 rows, 4 columns)
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr1_2d = arr1.reshape(3, 4)
print("Reshape to 3×4 matrix:")
print(f"Shape: {arr1_2d.shape}")
print(arr1_2d)
print()

# Example 2: Reshape 1D to 3D (2×3×2)
arr1_3d = arr1.reshape(2, 3, 2)
print("Reshape to 2×3×2 (3D array):")
print(f"Shape: {arr1_3d.shape}")
print(arr1_3d)
print()

# Example 3: Reshape 2D back to 1D using -1
arr_flat = arr1_2d.reshape(-1)
print("Flatten back to 1D:")
print(f"Shape: {arr_flat.shape}")
print(arr_flat)

Reshape to 3×4 matrix:
Shape: (3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshape to 2×3×2 (3D array):
Shape: (2, 3, 2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

Flatten back to 1D:
Shape: (12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]


### More Reshape Examples

In [ ]:
# Create a 4×4 matrix
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

print("Original 4×4 Matrix:")
print(arr)
print(f"Dimensions: {arr.ndim}D\n")

# Access single element at [row, column]
print("Element at position [0, 3]:", arr[0, 3])
print()

# Access entire column (column 3)
print("Entire column 3:")
print(arr[:, 3])
print()

# Access entire row (row 1)
print("Entire row 1:")
print(arr[1, :])
print()

# Access sub-matrix (rows 1-2, columns 2-3)
print("Sub-matrix (rows 1-2, columns 2-3):")
print(arr[1:3, 2:4])

2
4
[ 4  8 12 16]
[5 6 7 8]


In [9]:
# Advanced Slicing Examples

# Example 1: Access first two rows, all columns
print("First two rows:")
#print(arr[0:2, :])
print()

# Example 2: Access all rows, last two columns
print("All rows, last two columns:")
print(arr[:, 2:])
print()

# Example 3: Access diagonal elements
print("Diagonal elements:")
print(arr.diagonal())
print()

# Example 4: Reverse rows
print("Reversed rows (top to bottom):")
print(arr[::-1])
print()

# Example 5: Step slicing (every other row)
print("Every other row:")
print(arr[::2, :])

First two rows:

All rows, last two columns:


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### Advanced Slicing Examples

## Step 3: Array Slicing

### What is Slicing?
Slicing extracts specific elements or sub-arrays from a NumPy array. It's similar to slicing in Python lists but more powerful for multi-dimensional arrays.

### Slicing Syntax for 2D Arrays
- `arr[row, col]` - Access single element
- `arr[row_start:row_end, col_start:col_end]` - Access sub-array
- `arr[:, col]` - Access entire column
- `arr[row, :]` - Access entire row
- `arr[::-1]` - Reverse the array

### Example: Working with a 4×4 Matrix

In [ ]:
## Summary & Key Takeaways

### Array Reshaping
from numpy import spacing


- **Purpose**: Change array dimensions without changing data
- **Key Function**: `np.reshape()`
- **Important**: Total number of elements must remain constant
- **Tip**: Use `-1` to let NumPy calculate one dimension automatically
- **Use Cases**: 
  - Preparing data for neural networks
  - Converting between different matrix formats
  - Flattening multi-dimensional arrays

### Array Slicing
- **Purpose**: Extract specific elements or sub-arrays
- **Syntax**: `arr[row, col]` or `arr[row_start:row_end, col_start:col_end]`
- **Common Operations**:
  - `arr[:, col]` - Extract entire column
  - `arr[row, :]` - Extract entire row
  - `arr[::2, :]` - Extract every other row
  - `arr[::-1]` - Reverse array
- **Use Cases**:
  - Feature extraction in machine learning
  - Accessing specific data points
  - Data preprocessing and filtering

### Performance Tips
1. Use spacing instead of loops for better performance
2. Reshape operations are memory efficient (data isn't copied)
3. Use negative indices for reverse access: `arr[-1]` gets last element
4. Boolean indexing for conditional selection: `arr[arr > 5]`

### Common Mistakes to Avoid
-  Reshaping with incorrect total elements
-  Forgetting that Python uses 0-based indexing
-  Confusion between rows and columns in 2D arrays
-  Always check array shape before and after operations

---

**Author:** Sehar Shahzadi  
**Last Updated:** 2026  
**License:** Open Source